services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build:
      context: ./backend
    command: uvicorn main:api --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      -./backend/.env
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env